version: '3'
services:
  web:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/src
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
      build: ./docker/php
      depends_on:
        - mysql
      working_dir: /src
      volumes:
        - ./src:/src
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
